// This file is auto-generated by scripts/generate-db-types.ts.
// Do not edit this file manually.

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | { [key: string]: JsonValue } | JsonValue[];

export interface ProjectRow {
  id: string;
  slug: string;
  title: string;
  description: string | null;
  status: "draft" | "archived";
  created_at: string;
  updated_at: string;
}

export interface ProjectInsert {
  id: string;
  slug: string;
  title: string;
  description?: string | null;
  status?: "draft" | "archived";
  created_at?: string;
  updated_at?: string;
}

export interface ProjectUpdate {
  slug?: string;
  title?: string;
  description?: string | null;
  status?: "draft" | "archived";
}
