import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { Client } from "pg";

import { DbConfig } from "../src/config/db-config";
import { readDbConfig } from "../src/config/read-db-config";

interface EnumRow {
  enumName: string;
  enumValue: string;
}

interface ColumnRow {
  tableName: string;
  columnName: string;
  dataType: string;
  udtName: string;
  isNullable: "YES" | "NO";
  columnDefault: string | null;
  isIdentity: "YES" | "NO";
}

interface ColumnSpec {
  columnName: string;
  tsType: string;
  optional: boolean;
}

const OUTPUT_FILE = path.resolve(__dirname, "../src/types/generated.ts");
const IMMUTABLE_UPDATE_COLUMNS = new Set(["id", "created_at", "updated_at"]);
const EXCLUDED_TABLES = new Set(["knex_migrations", "knex_migrations_lock"]);

function quoteTypeLiteral(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function singularize(value: string): string {
  if (value.endsWith("ies")) {
    return `${value.slice(0, -3)}y`;
  }
  if (value.endsWith("s") && value.length > 1) {
    return value.slice(0, -1);
  }
  return value;
}

function toPascalCase(value: string): string {
  return value
    .split("_")
    .filter((segment) => segment.length > 0)
    .map((segment) => `${segment[0].toUpperCase()}${segment.slice(1)}`)
    .join("");
}

function withNullability(typeName: string, nullable: boolean): string {
  return nullable ? `${typeName} | null` : typeName;
}

function resolveType(row: ColumnRow, enumMap: Map<string, string[]>): string {
  const enumValues = enumMap.get(row.udtName);
  if (enumValues) {
    return enumValues.map((value) => quoteTypeLiteral(value)).join(" | ");
  }

  if (row.udtName === "uuid") {
    return "string";
  }
  if (row.udtName === "int8") {
    return "string";
  }
  if (row.udtName === "numeric") {
    return "string";
  }
  if (row.udtName === "json" || row.udtName === "jsonb") {
    return "JsonValue";
  }
  if (
    row.udtName === "date" ||
    row.udtName === "timestamp" ||
    row.udtName === "timestamptz"
  ) {
    return "string";
  }

  switch (row.dataType) {
    case "character varying":
    case "character":
    case "text":
    case "uuid":
      return "string";
    case "smallint":
    case "integer":
    case "real":
    case "double precision":
      return "number";
    case "boolean":
      return "boolean";
    case "numeric":
    case "decimal":
      return "string";
    case "date":
    case "timestamp without time zone":
    case "timestamp with time zone":
      return "string";
    case "json":
    case "jsonb":
      return "JsonValue";
    default:
      return "unknown";
  }
}

function renderInterface(interfaceName: string, columns: ColumnSpec[]): string[] {
  const lines = [`export interface ${interfaceName} {`];
  for (const column of columns) {
    const optionalSuffix = column.optional ? "?" : "";
    lines.push(`  ${column.columnName}${optionalSuffix}: ${column.tsType};`);
  }
  lines.push("}");
  lines.push("");
  return lines;
}

function buildGeneratedSource(tables: Map<string, ColumnRow[]>, enumMap: Map<string, string[]>): string {
  const lines: string[] = [];
  lines.push("// This file is auto-generated by scripts/generate-db-types.ts.");
  lines.push("// Do not edit this file manually.");
  lines.push("");
  lines.push("export type JsonPrimitive = string | number | boolean | null;");
  lines.push(
    "export type JsonValue = JsonPrimitive | { [key: string]: JsonValue } | JsonValue[];"
  );
  lines.push("");

  const sortedTableNames = Array.from(tables.keys()).sort();
  for (const tableName of sortedTableNames) {
    const tableRows = tables.get(tableName);
    if (!tableRows || tableRows.length === 0) {
      continue;
    }

    const typePrefix = toPascalCase(singularize(tableName));

    const rowColumns: ColumnSpec[] = tableRows.map((row) => ({
      columnName: row.columnName,
      tsType: withNullability(
        resolveType(row, enumMap),
        row.isNullable === "YES"
      ),
      optional: false
    }));

    const insertColumns: ColumnSpec[] = tableRows.map((row) => ({
      columnName: row.columnName,
      tsType: withNullability(
        resolveType(row, enumMap),
        row.isNullable === "YES"
      ),
      optional: row.columnDefault !== null || row.isIdentity === "YES"
    }));

    const updateColumns: ColumnSpec[] = tableRows
      .filter((row) => !IMMUTABLE_UPDATE_COLUMNS.has(row.columnName))
      .map((row) => ({
        columnName: row.columnName,
        tsType: withNullability(
          resolveType(row, enumMap),
          row.isNullable === "YES"
        ),
        optional: true
      }));

    lines.push(...renderInterface(`${typePrefix}Row`, rowColumns));
    lines.push(...renderInterface(`${typePrefix}Insert`, insertColumns));
    lines.push(...renderInterface(`${typePrefix}Update`, updateColumns));
  }

  while (lines[lines.length - 1] === "") {
    lines.pop();
  }

  return `${lines.join("\n")}\n`;
}

async function readEnums(client: Client, schema: string): Promise<Map<string, string[]>> {
  const result = await client.query<EnumRow>(
    `
      SELECT
        pg_type.typname AS "enumName",
        pg_enum.enumlabel AS "enumValue"
      FROM pg_type
      INNER JOIN pg_enum ON pg_enum.enumtypid = pg_type.oid
      INNER JOIN pg_namespace ON pg_namespace.oid = pg_type.typnamespace
      WHERE pg_namespace.nspname = $1
      ORDER BY pg_type.typname, pg_enum.enumsortorder
    `,
    [schema]
  );

  const enumMap = new Map<string, string[]>();
  for (const row of result.rows) {
    const values = enumMap.get(row.enumName);
    if (values) {
      values.push(row.enumValue);
      continue;
    }
    enumMap.set(row.enumName, [row.enumValue]);
  }

  return enumMap;
}

async function readColumns(client: Client, schema: string): Promise<Map<string, ColumnRow[]>> {
  const result = await client.query<ColumnRow>(
    `
      SELECT
        columns.table_name AS "tableName",
        columns.column_name AS "columnName",
        columns.data_type AS "dataType",
        columns.udt_name AS "udtName",
        columns.is_nullable AS "isNullable",
        columns.column_default AS "columnDefault",
        columns.is_identity AS "isIdentity"
      FROM information_schema.columns
      INNER JOIN information_schema.tables
        ON tables.table_schema = columns.table_schema
       AND tables.table_name = columns.table_name
      WHERE columns.table_schema = $1
        AND tables.table_type = 'BASE TABLE'
      ORDER BY columns.table_name, columns.ordinal_position
    `,
    [schema]
  );

  const tableMap = new Map<string, ColumnRow[]>();
  for (const row of result.rows) {
    if (EXCLUDED_TABLES.has(row.tableName)) {
      continue;
    }

    const tableColumns = tableMap.get(row.tableName);
    if (tableColumns) {
      tableColumns.push(row);
      continue;
    }
    tableMap.set(row.tableName, [row]);
  }

  return tableMap;
}

function createPgClient(config: DbConfig): Client {
  return new Client({
    host: config.host,
    port: config.port,
    user: config.user,
    password: config.password,
    database: config.database,
    ssl: config.ssl
  });
}

async function main() {
  const config = readDbConfig(process.env, { prefix: "DB" });
  const client = createPgClient(config);
  await client.connect();

  try {
    const [enumMap, tables] = await Promise.all([
      readEnums(client, config.schema),
      readColumns(client, config.schema)
    ]);
    const source = buildGeneratedSource(tables, enumMap);

    await mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
    await writeFile(OUTPUT_FILE, source, "utf8");

    console.info(
      `db:types wrote ${OUTPUT_FILE} (${tables.size} table${tables.size === 1 ? "" : "s"})`
    );
  } finally {
    await client.end();
  }
}

main().catch((error: unknown) => {
  console.error("db:types failed", error);
  process.exitCode = 1;
});
